Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'test/**/*.rb'
    - 'config/environments/*.rb'
AllCops:
  UseCache: false
  NewCops: enable
  Exclude:
    - 'config/environments/*'
